### ISSUE TITLE
Error handling response: TypeError: Error in invocation of tabs.get(integer tabId, function callback): No matching signature.

### ISSUE THREAD

**Issue by ProNotion** [jmfayard/search-tab-in-chrome-s-omnibox#11]
This is an extremely handy extension for me but recently stopped working. In the extensions manager it says there is an error, the details of which can be found below:

![image](https://user-images.githubusercontent.com/1590398/56943213-59b50980-6b16-11e9-9d08-c64e9ec9a093.png)

**Comment by ProNotion** [comment]
Sorry, this was not a fault of the package but it seems I was loading a local version I had tried to amend some time back.

**Comment by imankurnegi** [comment]
Showing the same for me. How you fixed it!!

**Comment by ProNotion** [comment]
> Showing the same for me. How you fixed it!!

As I mentioned previously, I was seeing the issue because I had made a change in my installed version and forgot to revert the change. I think I reinstalled the extension to fix the issue.
